seventh part of the story
thenishantsapkota/LSPP-Git-Assignment pull request #8
Opened 2023-05-11 03:42 UTC by shree404

7th part of the story

2023-05-11 12:37 UTC, shree404 commented
8th part of the story

2023-05-11 16:15 UTC, thenishantsapkota commented
@shree404 Can you resolve the merge conflicts?
Thank you :+1:

2023-05-11 17:43 UTC, thenishantsapkota requested changes

2023-05-11 17:43 UTC, thenishantsapkota commented on story.md
> +Feeling embarrassed, Bob had to spend the next several hours fixing all of the mistakes that the robot had made. From that day on, he never let his colleagues forget that even the most perfect progra
Part of the story is missing here.
Can you fix that?

2023-05-12 03:35 UTC, thenishantsapkota approved these changes

2023-05-12 03:35 UTC, thenishantsapkota commented
@12anupa-baral @jsurya860 Can you guys review this PR?
Thank you!

2023-05-12 06:20 UTC, jsurya860 approved these changes
all great but little confused in the last part

2023-05-12 06:20 UTC, jsurya860 commented on story.md
> +The incident with the robot taught Bob a valuable lesson about the importance of taking breaks and double-checking his work. He realized that sometimes, even the best programmers need to step away fr
Is this the conclusion or the missing part of the story?

2023-05-12 15:14 UTC, merged